### ISSUE TITLE
Translation for activity.md into Bengali

### ISSUE THREAD

**Issue by bellayet** [mozilla/mozilla-club-activity-html-puzzle-boxes#1]
---

title: HTML Puzzle Boxes
github: mozilla/mozilla-club-activity-html-puzzle-boxes
image: html-puzzleboxes.jpg
competencies:
### HTML ধাঁধার বাক্স

তৈরি করেছেন [ইউফি সেতিয়াওয়ান, মজিলা ইন্দোনেশিয়া](https://twitter.com/yofiesetiawan) এবং ক্লাবের জন্য রিমিক্স করেছে  [মজিলা](https://webmaker.org/mentor).

শিক্ষার্থীরা HTML ট্যাগ দেওয়া কাগজের বাক্সগুলো সঠিক ক্রমে সাঁজানোর প্রতিযোগিতা করবে, **সাধারণ কিছু HTML ট্যাগ এবং কিভাবে ওয়েব গড়ে ওঠে তার সাথে পরিচিত হবে**

৪৫ থেকে ৬০ মিনিট
### প্রস্তুতি

**সম্পূর্ণ করুন** [প্রাক-কার্যকলাপ প্রশ্নোত্তর](https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform)। কার্যকলাপের সাথে পরিচিত হতে এর কার্যকলাপ নিজে করুন। বাম পাশে "কার্যকলাপের জন্য পদক্ষেপ" অংশে থাকা ভিডিও দেখুন।

ধাঁধার বাক্সকের প্যাটার্ন [অন্তত ১২ কপি প্রিন্ট করুন](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0)।

> একটি ধাঁধার বাক্স তৈরি করা খুব সহজ। কিন্তু, এই খেলাটি খেলতে হলে আপনাকে যথেষ্ট পরিমাণে ধাঁধার বাক্স তৈরি করতে হবে, যথেষ্ট পরিমাণে ওপেনিং ট্যাগ ও ক্লোজিং ট্যাগ নিশ্চিত করতে – আপনার অন্তত ১২ টি বাক্সের প্রয়োজন হবে। সর্বমোট, এক জোড়া খেলোয়ারের জন্য, আপনার প্রয়োজন হবে ২৪টি বাক্স। তাই, ২৪টি বাক্স তৈরি করতে, আপনাকে ১২টি পেপারক্রাফট প্যাটার্ণ শীট প্রিণ্ট করতে হবে।
> 
> পাতলা কাগজে ধাঁধার বাক্স প্রিন্ট করা ভাল, যেন এটি সহজে এবং সুন্দরভাবে তৈরি করা যায়।
> 
> আপনার হাতে যদি সময় কম থাকে, তাহলে আপনি এই কার্যকলাপটি বাক্স তৈরির বদলে এক টুকরো কাগজে বা পোস্ট-ইটে লিখেও করতে পারেন।

শিক্ষার্থীরা কি [প্রাক-কার্যকলাপ প্রশ্নোত্তর](https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform) সম্পূর্ণ করেছে। 

---

১৫<br>মিনিট
### পরিচিতি: বাক্স তৈরি

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

মজার জিনিষ কিন্তু সময় সাপেক্ষ ব্যাপার। শিক্ষার্থীরা প্রথমে তাদের বাক্সগুলো তৈরি করবে। বোনাস: যদি সময় পাওয়া যায়, স্টেশনে সংকেত দেওয়ার জন্য বাক্সগুলো দিয়ে মেন্টর [HTML Corners](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) খেলবেন।

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

২০<br>মিনিটি
### HTML ধাঁধার বাক্স চ্যালেঞ্জ

প্রথমে একটি ছোট দলে ট্যাগগুলোকে সঠিক ক্রমে সাঁজান। তারপর প্রতিযোগিতা করুন!

![স্তুপীকৃত বাক্স](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

HTML ট্যাগ গঠনে এটি সঠিক সমাহার।

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

১০<br>মিনিট
### প্রতিফলন: ট্যাগ পর্যবেক্ষণ

যদি সময় পাওয়া যায় তাহলে [HTML Corners খেলা](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners)  পুনরায় খেলুন। অথবা, ছাত্ররা চিৎকার করে বলবে প্রতিটি ট্যাগের অর্থ কি।

বোনাস: যদি সময় পাওয়া যায়, কোন পাতার "View Source" ক্লিক করে বা X-Ray Goggles ব্যবহার করে দেখান কোন ট্যাগ কি কাজ করে। বোনাস: উলট পালট HTML ধাঁধার বাক্স বা পোস্ট-ইট নোটগুলো পুনরায় সাঁজিয়ে আপনার আশেপাশের পরিবেশকে মার্কাপ মিক্সারে পরিণত করুন।

আপনার গ্রুপকে জিজ্ঞাসা করুন তারা কি পেল এবং খেলা শেষ করুন।

**Comment by soapdog** [comment]
:+1: Thanks a lot for the support! This translation is now live at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#bn 

We can now reach even more people with our activities thanks to your effort :smile_cat:
