### ISSUE TITLE
Localization of aside.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-html-puzzle-boxes#10]
#### दर्शक
-  ८ +
-  प्रणाली विचारकों से शुरुआत
#### सामग्री
- [मुद्रित एचटीएमएल पहेली के डिब्बे ](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) मोटे कागज पर. १२ प्रतियां न्यूनतम.
- गोंद या टेप
- कैंची
#### सीखने का  मकसद
- सबसे अधिक इस्तेमाल किये जाने वाले  एचटीएमएल टैग्स को संक्षेप में लिखे 
- एक वेब पेज - संरचना के लिए फिर से एचटीएमएल टैग का प्रयोग करें
- विशिष्ट दर्शकों के लिए एक वेब पेज बनाये 
#### गतिविधि में कार्रवाई करें !

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>जकार्ता, इंडोनेशिया में हुए एचटीएमएल पहेली डिब्बों की चुनौती की वीडियो </small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>फोस्सास्या सिंगापुर  में हुए एचटीएमएल पहेली डिब्बों की चुनौती की वीडियो</small></a>

समुदाय रीमिक्स देखें
हमारे [चर्चा मंच] में शिक्षकों और कार्यकर्ताओं को उनकी विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है तरीकों की जाँच करें(http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3).

**Comment by soapdog** [comment]
Awesome work!!! Thanks a lot for this contribution. It is live at:

http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#hi

Just please review the live page because I had to change some of the source code because there were syntax errors in the Markdown links.

Thanks again for your support and hard work! :smile_cat:
