### ISSUE TITLE
Translation of aside.md into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-html-puzzle-boxes#13]
#### Publiek
- 8+
- beginnende systeemdenkers
#### Materialen
- [Afgedrukte HTML Puzzeldozen](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) op dik papier. Minimum 12 exemplaren.
- Lijm of plakband
- Schaar
#### Leerdoelstellingen
- De meest gebruikte HTML tags samenvatten
- HTML tags gebruiken om een webpagina te reconstrueren
- Een webpagina maken voor een bepaald publiek
#### Activiteit in Actie!

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>Video van de HTML Puzzeldoos Challenge in Jakarta, Indonesië</small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>Video van de HTML Puzzeldoos Challenge van FOSSASIA in Singapore</small></a>

Bekijk re-mixes van de gemeenschap
Kijk ook eens naar de manieren waarop leerkrachten en activisten deze activiteit hebben aangepast aan hun eigen publiek in ons [Discussie Forum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3).

**Comment by soapdog** [comment]
Awesome work!!! Thanks a lot for this contribution. It is live at:

http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#nl

:smile_cat:
