### ISSUE TITLE
Translation of activity.md into Dutch

### ISSUE THREAD

**Issue by gvanwaelvelde** [mozilla/mozilla-club-activity-html-puzzle-boxes#14]
---

title: HTML Puzzle Boxes
github: mozilla/mozilla-club-activity-html-puzzle-boxes
image: html-puzzleboxes.jpg
competencies:
### HTML Puzzeldozen

Gemaakt door [Yofie Setiawan, Mozilla Indonesië](https://twitter.com/yofiesetiawan) en geremixt voor Clubs door [Mozilla](https://webmaker.org/mentor).

Leerlingen zullen zo snel mogelijk de papieren dozen met HTML tags in volgorde plaatsen, en zo **de meest gebruikte HTML tags en structuur van een webpagina leren kennen**. 

45 minuten tot een uur
### Voorbereiding

**Vul de** [voorbereidingsvragenlijst](https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform) in. Doe de activiteit eerst zelf om ze te leren kennen. Bekijk de video links onder "Activiteit in Actie".

[Druk minstens 12 exemplaren af](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) van het Puzzeldoos-patroon.

> Een Puzzeldoos maken is vrij makkelijk. U heeft minstens 12 Puzzeldozen nodig om het spel te spelen – om zeker te zijn dat er genoeg dozen zijn met open -en sluit tags. Voor twee spelers heeft u, in totaal, 24 dozen nodig. Om 24 dozen te maken, moet u 12 exemplaren afdrukken van het papieren patroon.
> 
> Het is aan te raden om de Puzzeldozen op dik papier te drukken, dat maakt het makkelijker om ze in elkaar te zetten en zo zijn ze steviger.
> 
> Als u weinig tijd hebt, kunt u deze activiteit ook doen door de tags op stukjes papier of post-its te schrijven in plaats van dozen te maken.

Laat leerlingen hun [voorbereidingsvragenlijst](https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform) invullen. 

---

15<br>min
### Inleiding: De dozen maken

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

Dozen maken is leuk, maar kost veel tijd. Eerst maken de leerlingen hun dozen. Bonus: Als er tijd genoeg is, kunt u het spel [HTML Corners](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) spelen met de dozen.

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

20<br>min
### HTML Puzzeldoos Uitdaging

Sorteer de tags eerst in een kleine groep in de juiste volgorde. Dan begint het spel!

![stapel dozen](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

Dit is de juiste combinatie van de HTML tags structuur.

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

10<br>min
### Ten slotte: Over de tags nadenken

Speel het [HTML Corners spel](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) als er tijd voor is. Of, laat de leerlingen uitroepen wat elke tag betekent.

Bonus: Als er voldoende tijd is, laat de tags in actie zien door op "Paginabron bekijken" te klikken of gebruik de X-Ray Goggles op een webpagina. Bonus: Tag uw omgeving door geremixte HTML Puzzeldozen of post-its in de kamer te plaatsen zoals in Markup Mixer.

Eindig met aan de groep te vragen om hun bevindingen te bespreken.

**Comment by soapdog** [comment]
Awesome work!!! Thanks a lot for this contribution. It is live at:

http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#nl

:smile_cat:
