### ISSUE TITLE
Localization of activity.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-html-puzzle-boxes#15]
---

शीर्षक: HTML Puzzle Boxes
गिटहब : मोज़िला/मोज़िला-सभा-गतिविधि-एचटीएमएल-पहेली-के-डिब्बे
तस्वीर: एचटीएमएल-पहेली-के-डिब्बे.जेपीजी 
दक्षताओं:
### एचटीएमएल पहेली के डिब्बे

[ योफी सेतियावान , मोज़िला इंडोनेशिया] द्वारा बनाया गया(https://twitter.com/yofiesetiawan) और [ मोज़िला ] क्लब द्वारा रिमिक्स (https://webmaker.org/mentor).

शिक्षार्थियों एचटीएमएल टैग के साथ लेबल कागज के डिब्बे को अनुक्रम में करने के लिए दौड़ होगी, *_सबसे आम एचटीएमएल टैग से परिचित हों और कैसे एक वेब पेज संरचना करें *_.

४५ मिनट से एक घंटा 
### तैयारी

**[ पूर्व गतिविधि प्रश्नावली ] को पूरा करें(https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform). गतिविधि से परिचित होने के लिए उससे खुद से करें। अपनी बाईं ओर "गतिविधि में कार्य " शीर्षक के निचे वीडियो देखें !

[कम से कम 12 प्रतियां प्रिंट करें ](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) पहेली बॉक्स पैटर्न की ।

> एक पहेली बॉक्स बनाना बहुत आसान है. लेकिन, खेल खेलने के लिए पर्याप्त पहेली बक्से होने चाहिए , आपको कम से कम 12 बक्से की आवश्यकता होगी – आप उद्घाटन और समापन टैग के लिए पर्याप्त बक्से है यह सुनिश्चित कर लें . कुल में, खिलाड़ियों की एक जोड़ी के लिए , आप 24 बक्से बनाने की जरूरत है । तो, सभी 24 बक्से का निर्माण करने के लिए , आप पेपरक्राफ्ट पैटर्न के 12 चादरें प्रिंट की जरूरत है।
> 
> यह मोटे कागज के साथ पहेली बॉक्स मुद्रित करने के लिए बेहतर है , इसलिए इसे इकट्ठा करने के लिए आसान हो जाएगा और एक बेहतर निर्माण होगा।
> 
> अगर आपके पास समय कम हैं , तो आप ये गतिविधि कागज के टुकड़ो पर लिख के भी कर सकते हैं उसके डिब्बे बनाने के बजाये !

शिक्षार्थियों उनके [ पूर्व गतिविधि प्रश्नावली ] पूरा करना है(https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform). 

---

१५ <बी आर > मिनट 
### परिचय: बक्से बनाने

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

यह बहुत मजेदार है, लेकिन समय लेने वाला काम करना है. शिक्षार्थियों पहले अपने बक्से इकट्ठा करें . बोनस: अगर समय परमिट देता है  , तो संरक्षक [एचटीएमएल कोनों ] खेल सकता है (https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) बक्से का उपयोग स्टेशनों को संकेत करने के लिए कर सकते है ।

![छवि का नमूना](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![छवि का नमूना](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

२० <बी आर >मिनट  
### एचटीएमएल पहेली बॉक्स चैलेंज

सबसे पहले एक छोटे से समूह में सही क्रम में टैग इकट्ठा करें । फिर दौडे  !

![खड़ी बक्से](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

यह एचटीएमएल टैग संरचना का सही संयोजन है।

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

१० <बी आर >मिनट  
### चिंतन: टैग की समीक्षा

[एचटीएमएल कोनों खेल ] को दोहराएँ(https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) अगर समय आज्ञा देता है .या , बस छात्रों को बोल कर बताना होगा की सरे टैग का क्या मतलब होता है 

बोनस: समय आज्ञा देता है तो , " स्रोत देखेने के लिए " क्लिक करने या एक वेबपेज पर एक्स- रे काले चश्मे का उपयोग करके कार्रवाई में टैग देखें ! बोनस : अपने पर्यावरण को एचटीएमएल पहेली डिब्बो की सहायता से टैग करें या फिर उसको अपने नोट्स की तरह अ ला  मार्कअप मिक्सर कमरे में लगाएं !

अपने समूह से पूछे की उन्हें इस गतिविधि में क्या मिला और उसके बाद ये समाप्त करें !

**Comment by soapdog** [comment]
Awesome work!!! Thanks a lot for this contribution. It is live at:

http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#hi

Just please review the live page because I had to change some of the source code because there were syntax errors in the Markdown links.

Thanks again for your support and hard work! :smile_cat:
