### ISSUE TITLE
Localization of aside.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-html-puzzle-boxes#17]
#### Målgrupp
- 8+
- Begynnande källkritiker
#### Material
- [Utskrivna HTML Pussel Lådor](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) på tjockt papper. 12 kopior minst.
- Lim eller tejp
- Saxar
#### Lärandemål
- Summera dom oftast HTML taggarna
- Använd HTML taggar för att omstrukturera en hemsida 
- Skapa en hemsida för ett specific audience
#### Aktiviteten på riktigt!

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>Video av HTML Puzzle Box Challenge i Jakarta, Indonesien</small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>Video av HTML Puzzle Box utmaningen på FOSSASIA i Singapore</small></a>
#### Se remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt [Diskussionsforum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3). 

(Not sure if all Markdown is perfect tough first time i am writing Markdown so you better check)

**Comment by soapdog** [comment]
The markdown looks great! Thanks again for your continuous support!

I've added that to the repo but I can't enable Swedish translation until we get activity.md done :-) your markdown skills are very good, do not worry! :smile_cat:

**Comment by bittin** [comment]
Activity.md here: 

---

title: HTML Puzzle Boxes
github: mozilla/mozilla-club-activity-html-puzzle-boxes
image: html-puzzleboxes.jpg
competencies:

##   - {label: "Composing for the web", type: "composing"}

## [Sektion 2. Skriva för Webben](http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/)

### HTML Pussel Lådor

Skapad av [Yofie Setiawan, Mozilla Indonesien](https://twitter.com/yofiesetiawan) och remixad för Clubs av [Mozilla](https://webmaker.org/mentor).

Studenterna kommer köra ett race genom att sekvensera pappers lådor märkta Med HTML taggar, **bli bekant med de vanligaste HTML taggarna och hur man ska strukturera en webbsida**.

45 minuter till en timme

### Förberelser

**Genomför den** [förberedande Enkäten](https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform). Gör sedan aktiviteten själv för att bekanta dig med den. Se videon till vänster under "Activity in Action".

[Skriv ut minst 12 kopior](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) av detta Pussel låde mönster.

> Skapa en Pussel låda är rätt enkelt. Men, för att ha tillräckligt med pussel lådor för att spela detta spel, så krävs det åtminstonde 12 lådor – för att se till att du har tillräckligt med lådor för att öppna och stänga taggar. Totalt, för ett par av spelare, så behöver du bygga 24 lådor. Så, för att totalt bygga alla 24 lådor, så behöver du skriva ut  12 ark av papercraft mönster.
> 
> Det är föredraget att skriva ut Pussel lådorna med tjockt papper, så att dom går enklare att sätta ihop och bygga bättre. 
> 
> Om du har dåligt med tid, så kan du göra denna aktiviteten genom att skriva på några papper eller post-its istället för att göra lådor.

Få dom studerande att slutföra deras [pre-aktivitet frågeformulär](https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform).

---

15<br>min

### Introduktion: Göra lådorna

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

Detta är rätt så roligt men tar tid att göra. Dom studerande byggar först deras lådor. Bonus: Om ni har tid över, mentorn spelar [HTML Corners](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) med hjälp av lådorna för att signalera stationer.

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

20<br>min

### HTML Pussel Lådors utmaningen

Först bygg ihop HTML taggarna i rätt ordning i en liten grupp. Sedan Race!

![stacked boxes](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

Detta är den rätta kombinationen av en HTML taggarnas struktur.

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

10<br>min

### Reflektion: Granska Taggarna

Upprepa [HTML Corners spelet](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) om ni har tid över. Eller, bara få studenterna att ropa ut vad varje HTML tagg betyder.

Bonus: Om ni har tid över, visa vad HTML taggarna används till in action genom att klicka på "Visa källkod" eller använda X-Ray Goggles på en hemsida. Bonus: Tag i din omgivning genom att sätta ut remixade HTML Pussel lådor eller post-it lappar runt om i rummet a la Markup Mixer.

Avsluta genom att be gruppen att reflektera över vad de hittade.
