### ISSUE TITLE
Translation for aside.md into Bengali

### ISSUE THREAD

**Issue by bellayet** [mozilla/mozilla-club-activity-html-puzzle-boxes#2]
#### দর্শক
- ৮+
- সিস্টেম চিন্তাবিদের শুরু
#### উপকরণ
- পাতলা কাগজে [প্রিন্ট করা HTML ধাঁধার বাক্স](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0)। নূন্যতম ১২ কপি।
- আঠা অথবা টেপ
- সিজর বা কেচি
#### শিক্ষণের উদ্দেশ্য
- সাধারণত ব্যবহৃত হয় এম কিছু HTML tags এর সাথে পরিচিত হওয়া
- HTML ট্যাগ ব্যবহার করে একটি পাতাকে পুনরায় গঠন করা
- নির্দিষ্ট দর্শকের জন্য একটি ওয়েব পেইজ তৈরি করা
#### কার্যকলাপের জন্য পদক্ষেপ!

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>Video of the HTML Puzzle Box Challenge in Jakarta, Indonesia</small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>Video of the HTML Puzzle Box Challenge at FOSSASIA in Singapore</small></a>

কমিউনিটি রিমিক্সগুলো দেখুন
[আলোচনা ফোরাম] এ দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে (http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3)।

**Comment by soapdog** [comment]
:+1: Thanks a lot for the support! This translation is now live at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#bn 

We can now reach even more people with our activities thanks to your effort :smile_cat:
