### ISSUE TITLE
Translation for aside.md into Filipino

### ISSUE THREAD

**Issue by ericfajardo** [mozilla/mozilla-club-activity-html-puzzle-boxes#5]
#### Mga gagamit
- 8+
- para sa mga kabataang may mapanuring pag iisip
#### Materyales
- [Naka-print na Printed HTML Puzzle Boxes](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) sa makapal na papel. Pinakamababa sa 12 na kopya
- Pang dikit o tape
- Guting
#### Mga Layuning Matutunan
- Upang Ilagom ang pang karaniwang ginagamit na HTML tags
- Gamitin ang HTML tags para baguhin ang anyo ng isang web page
- Gumawa ng isang web page para sa partikular na manonood
#### Ginagawa sa Aksyon!

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>Video ng HTML Puzzle Box Challenge in Jakarta, Indonesia</small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>Video ng HTML Puzzle Box Challenge at FOSSASIA in Singapore</small></a>
#### Tignan ang gawa ng ibang kumunidad

Tignan ang ibat-ibang paraan kung paano binago ng mga tagapagturo ang aktibidad na ito depende sa mga gagamit sa ating [Discussion Forum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3).

**Comment by soapdog** [comment]
:smile_cat: thanks a lot for your hard work.

Your awesome L10N is now available at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#fil
