### ISSUE TITLE
Translation for activity.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-html-puzzle-boxes#6]
---

title: HTML Puzzle Boxes
github: mozilla/mozilla-club-activity-html-puzzle-boxes
image: html-puzzleboxes.jpg
competencies:
### HTML Puzzle-Boxen

Produziert von [Yofie Setiawan, Mozilla Indonesien](https://twitter.com/yofiesetiawan) und remixed für Clubs von [Mozilla](https://webmaker.org/mentor).

Die Lernenden werden darum wetteifern, die Papier-Boxen mit HTML-Tags beschriften, **um so mit den geläufigsten HTML-Tags und der Struktur einer Web-Seite vertraut zu werden**.

45 Minuten bis einer Stunde
### Vorbereitung

**Beantworte den** [Vorbereitungs-Fragebogen](https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform). Absolviere die Übung selber, um dich damit vertraut zu machen. Sieh dir das Video links unter "Aktivität bei der Arbeit" an.

[Drucke mindestens 12 Kopien](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) der Puzzle-Box-Vorlagen aus.

> Eine Puzzle-Box anzufertigen ist ziemlich einfach. Aber um genug Puzzle-Boxen für das Spiel zu haben, brauchst du mindestens 12 - dadurch stellst du sicher, genug Boxen für öffnende und schließende Tags zu haben. Damit brauchst du für jedes Spieler-Pärchen 24 Boxen. Darum musst du 12 Vorlagen ausdrucken, um die 24 Boxen anfertigen zu können.
> 
> Vorzugsweise sollten die Puzzle-Boxen auf dickem Papier ausgedruckt werden, damit sie leichter zum Basteln und stabiler sind.
> 
> Wenn du nur wenig Zeit hast, kannst du die Aktivität auch mit Post-Its oder beschrifteten Zetteln anstelle von Boxen absolvieren.

Lass die Lernenden ihren eigenen [Vorbereitungs-Fragebogen](https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform) ausfüllen.

---

15<br>min
### Einführung: Die Boxen anfertigen

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

Es macht zwar viel Spaß, dauert aber auch lange. Die Lernenden basteln zuerst die Boxen. Bonus: Falls es die Zeit zulässt, können die Mentoren [HTML Corners](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) mit den Boxen spielen, um die Stationen zu signalisieren.

![Beispiel-Bild](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![Beispiel-Bild](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

20<br>min
### HTML Puzzle-Box-Wettbewerb

Ordne die Tags zunächst in einer kleinen Gruppe in der richtigen Reihenfolge an. Dann spielt!

![Gestapelte Boxen](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

Dies ist die richtige Kombination der HTML-Tags-Struktur.

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

10<br>min
### Reflexion: Über Tags nachdenken

Wieder das [HTML Corners-Spiel](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners), sofern es die Zeit zulässt. Andernfalls lass die Schüler reinrufen, welche Bedeutung jeder Tag hat.

Bonus: Falls es die Zeit erlaubt, führe die Tags in Aktion vor, indem du auf "Quellcode ansehen" klickst oder die Röntgen-Brille auf der Web-Seite anwendest. Bonus: Versehe deine Umgebung mit Tags, indem du remixte HTML-Puzzle-Boxen oder Post-It-Notizen wie im Markup Mixer im Raum verteilst.

Schließe die Runde damit, die Gruppe zu bitten, zu reflektieren, was sie gelernt haben.

**Comment by soapdog** [comment]
:smile_cat: :smiley_cat: :smile_cat: your translation is live at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#de

Thanks a lot for your continuous support! You rock!
