### ISSUE TITLE
Translation for aside.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-html-puzzle-boxes#7]
#### Publikum
- 8+
- Beginner im systematischen Denken
#### Material
- [Ausgedruckte HTML-Puzzle-Boxen](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) auf dickem Papier. Mindestens 12 Kopien
- Kleber oder Tape
- Scheren
#### Lernziele
- Fasse die üblichsten HTML-Tags zusammen
- Benutze HTML-Tags, um eine Web-Seite neu zu strukturieren
- Erstelle eine Web-Seite für eine bestimmte Zielgruppe
#### Aktivität bei der Arbeit!

<iframe src="https://www.youtube-nocookie.com/embed/0lj_nkmwMF4?rel=0" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
<a href="https://www.youtube.com/watch?v=0lj_nkmwMF4"><small>Video des HTML-Puzzle-Box-Wettbewerbs in Jakarta, Indonesien</small></a>

<iframe src="https://www.youtube-nocookie.com/embed/_LFaWJqRi64?t=1m" allowfullscreen="" frameborder="0" height="215px" width="100%"></iframe><br>
                <a href="https://youtu.be/_LFaWJqRi64?t=1m"><small>Video des HTML-Puzzle-Box-Wettbewerbs auf der FOSSASIA in Singapur</small></a>

 Weitere Community-Remixes

Siehe auch weitere Wege in unserem [Diskussions-Forum](http://discourse.webmaker.org/t/testing-2-writing-the-web/1195/3), wie Lehrende und Aktivisten diese Aktivität für ihr Publikum abgewandelt haben.

**Comment by soapdog** [comment]
:smile_cat: :smiley_cat: :smile_cat: your translation is live at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#de

Thanks a lot for your continuous support! You rock!
