### ISSUE TITLE
Translation for activity.md into Filipino

### ISSUE THREAD

**Issue by ericfajardo** [mozilla/mozilla-club-activity-html-puzzle-boxes#8]
---

title: HTML Puzzle Boxes
github: mozilla/mozilla-club-activity-html-puzzle-boxes
image: html-puzzleboxes.jpg
competencies:
### HTML Puzzle Boxes

Ginawa ni [Yofie Setiawan, Mozilla Indonesia](https://twitter.com/yofiesetiawan) and remixed for Clubs by [Mozilla](https://webmaker.org/mentor).

Ang Mag aaral ay mag uunahan sa pagkakasunod sunod ng papel na kahon na may nakasulat na HTML tags, **para maging pamilyar sa pang karaniwang ginagamit na HTML tags at kung ano ang estruktura ng isang web page**.

45 minuto hanggang isang oras
### Preperasyon

**Kumpletuhin ang** [naka preperang aktibidad na sasagutan](https://docs.google.com/a/mozillafoundation.org/forms/d/1IFhGuK4h7YqxqoUP880_hYV0S8TYEv0sBCbRNBy-0f4/viewform).Gawin ang aktibidad ng mag isa upang maging pamilyar dito. Tignan ang video sa bandang kaliwa, sa ilalim ng "Activity in Action".

[Mag-Print ng hindi bababa sa 12 kopya](https://www.dropbox.com/s/lv7u8tqawawudiy/html-puzzle-box.pdf?dl=0) ng Puzzle Box pattern.

> Gumawa ng isang Puzzle Box box ay madali lamang. Pero, para magkaroon ng sapat na Puzzle Boxes para malaro ito, kailangan ng hindi bababa sa 12 boxes ang kakailanganin – para maging sigurado na sapat ang boxes para sa pag sara at pag bukas ng tags. Sa Kabuoan, para sa isang paheras na kalahok, kailangan bumuo ng 24 boxes. Para makagawa ng 24 boxes kakailanganin ng 12 piraso ng papaercraft pattern.
> 
> Ito ay higit na mabuti na iprint ang Puzzle Box sa makapal na papel, para ito ay madali lamang buoin at magkaroon ng matibay na pagkakagawa. 
> 
> Kung ang iyong oras ay limitado, pwede mong gawin ang aktibidad na ito sa pamamagitan ng pag sulat sa isang papel o kaya sa isang post-its/sticky notes sa halip na gumawa pa ng mga kahon.

Ang mag aaral ay kailangan kumpletuhin ang [nakapreperadong aktibidad na sasagutan](https://docs.google.com/a/mozillafoundation.org/forms/d/1i-fPxOGeuq-yxhEx-DYrf_Vj0WHqFpWcsUgF_l6ffOk/viewform). 

---

15<br>minuto
### Introduksyon: Gumawa ng Kahon

<iframe src="https://www.youtube.com/embed/eWXCZNDBl04?rel=0" allowfullscreen="" frameborder="0" height="460px" width="100%"></iframe>

Ito ay masayang gawain subalit nangangailangan ng masinsinang atensyon. Pagbuo ng kahon ang kinakailangang unang gagawin ng mga mag-aaral (learners). Bonus: Kung may natitira pang oras, ang tagapagturo ay maglalaro[HTML Corners](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) bilang sensyales sa susunod na istasyon.

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-01.jpg)

![img sample](http://yopdesign.com/images/webmaker/html-puzzle-box-step-02.jpg)

---

20<br>minuto
### HTML Puzzle Box Challenge

Una ay ayusin ang tags sa tamang pag kakasunod sa maliit na group. at mag unahan !

![stacked boxes](http://yopdesign.com/images/webmaker/html-puzzle-box-game-01.jpg)

Ito ang tamang kombinasyon ng HTML tags structure.

```
<html>
    <head>
        <title>
        </title>
        <style>
        </style>
    </head>
    <body>
        <p>
        </p>
    </body>
</html>
```

---

10<br>minuto
### Repleksyon: Suriin ang Tags

Ulitin muli ang [HTML Corners game](https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners) kung may pahintulot na oras. o Mag tawag ng estudyante upang makapag bigay ng kanilang idea kung ano ang bawat tags

Bonus: Kung may natitira pang oras, ipakita ang kumikilos na mga tag sa pamamagitan ng pagpindot sa "View Source" o gamit ang the XRay Goggles sa webpage. Bonus: I-tag ang iyong paligid sa pamamagitan ng aglagay ng pinaghalong HTML Puzzle Boxes o 'post-it notes sa paligid ng kuwarto katulad ng Markup Mixer.

Tapusin ito sa pamamagitan ng pagtatanong sa grupo kung ano ang kanilang natagpuan.

**Comment by soapdog** [comment]
:smile_cat: thanks a lot for your hard work.

Your awesome L10N is now available at http://mozilla.github.io/mozilla-club-activity-html-puzzle-boxes/#fil
